export const portfolios = [
  {
    id: "01",
    image: "https://i.ibb.co/Wf1HVc3/car3.jpg",
    name: "My First Portfolio",
    category: "full-stack projects",
  },
  {
    id: "02",
    image: "https://i.ibb.co/Wf1HVc3/car3.jpg",
    name: "My First Portfolio",
    category: "full-stack projects",
  },
  {
    id: "03",
    image: "https://i.ibb.co/Wf1HVc3/car3.jpg",
    name: "My First Portfolio",
    category: "full-stack projects",
  },
  {
    id: "04",
    image: "https://i.ibb.co/Wf1HVc3/car3.jpg",
    name: "My First Portfolio",
    category: "full-stack projects",
  },
  {
    id: "05",
    image: "https://i.ibb.co/Wf1HVc3/car3.jpg",
    name: "My First Portfolio",
    category: "full-stack projects",
  },
  {
    id: "06",
    image: "https://i.ibb.co/Wf1HVc3/car3.jpg",
    name: "My First Portfolio",
    category: "full-stack projects",
  },
  {
    id: "07",
    image: "https://i.ibb.co/Wf1HVc3/car3.jpg",
    name: "My First Portfolio",
    category: "full-stack projects",
  },
  {
    id: "08",
    image: "https://i.ibb.co/Wf1HVc3/car3.jpg",
    name: "My First Portfolio",
    category: "full-stack projects",
  },
  {
    id: "09",
    image: "https://i.ibb.co/Wf1HVc3/car3.jpg",
    name: "My First Portfolio",
    category: "full-stack projects",
  },
  {
    id: "10",
    image: "https://i.ibb.co/Wf1HVc3/car3.jpg",
    name: "My First Portfolio",
    category: "full-stack projects",
  },
  {
    id: "11",
    image: "https://i.ibb.co/Wf1HVc3/car3.jpg",
    name: "My First Portfolio",
    category: "full-stack projects",
  },
  {
    id: "12",
    image: "https://i.ibb.co/Wf1HVc3/car3.jpg",
    name: "My First Portfolio",
    category: "full-stack projects",
  },
  {
    id: "13",
    image: "https://i.ibb.co/Wf1HVc3/car3.jpg",
    name: "My First Portfolio",
    category: "full-stack projects",
  },
];
